### ISSUE TITLE
Remember Window Position and Size

### ISSUE THREAD

**Issue by danny8k** [GoogleChromeLabs/picture-in-picture-chrome-extension#11]
Hi team,

I don't know if this would be possible considering this is a new API. But it would be nice to configure the position where the PIP window will open (or remember the past position). Similar to how js allows control over the size and position of popup windows. 

Thanks for the hard work.

**Comment by beaufortfrancois** [comment]
Hey @danny8k,
It should remember last position in the same tab session. Is it not the case for you?

**Comment by danny8k** [comment]
Hi @beaufortfrancois,
Yeah, position is remembered for the same tab-session. However, I was thinking that it would be a nice feature to remember the position and size of the popup between sessions. It doesn't have to be per site, globally would be fine. This would save a lot of time, moving, resizing the window.

**Comment by frankjoke** [comment]
Yes, to remember size and position would be great! I have to resize/move all time because the small size (on 4k monitor) and the lower right does not fit me at all!
Otherwise great work ...

**Comment by beaufortfrancois** [comment]
I agree with this. You can star https://bugs.chromium.org/p/chromium/issues/detail?id=910431 to be updated when this will be addressed.
