### ISSUE TITLE
Chrome 73 extension doesnt work

### ISSUE THREAD

**Issue by gh0sti** [GoogleChromeLabs/picture-in-picture-chrome-extension#13]
running chrome beta 73 extension stopped working on youtube

**Comment by beaufortfrancois** [comment]
Which OS are you running?
Chrome OS, Linux, macOS, Windows?

**Comment by gh0sti** [comment]
Windows 10

**Comment by beaufortfrancois** [comment]
Can you open DevTools console and share logs (or a screenshot)?

**Comment by gh0sti** [comment]
Works with chrome 74
