### ISSUE TITLE
PiP extension doesn't work on FreeBSD

### ISSUE THREAD

**Issue by cpu82** [GoogleChromeLabs/picture-in-picture-chrome-extension#17]
Hi,

It seems that the extension does not work on FreeBSD. Chromium 72.0.3626.119 stops working and crashes with any YouTube video. 

Would it be possible to support FreeBSD?

Thanks

**Comment by beaufortfrancois** [comment]
Thanks @cpu82 for your feedback!

Do you mind creating a bug at crbug.com/new and provide javascript errors you may notice in the developer console if possible?

**Comment by cpu82** [comment]
Picture in picture mode for video works after updating chromium to 73.0.3683.103.

**Comment by beaufortfrancois** [comment]
Glad to hear this!
