### ISSUE TITLE
Please upgrade chrome store plugin

### ISSUE THREAD

**Issue by him0** [GoogleChromeLabs/picture-in-picture-chrome-extension#2]
Version: 69.0.3497.81（Official Build） （64 bits）

When Installing this extension from chrome store, it doesn't works well, but installing from source code it works well. It seems store's extension is not latest version. please upgrade.

**Comment by Prinmode** [comment]
The same here, fails from Chrome Store, but from here work perfectly.

**Comment by beaufortfrancois** [comment]
Which version of Chrome do you have?
It works great for me.

**Comment by Prinmode** [comment]
This version: 69.0.3497.100 (Build oficial) (64 bits)

**Comment by beaufortfrancois** [comment]
Can you upgrade to Chrome 70?

**Comment by Prinmode** [comment]
I got version 70.0.3538.77 (official build) (64 bits), removed the installed extension from source, installed from chrome store and now it works 👍

**Comment by beaufortfrancois** [comment]
Thanks!
