### ISSUE TITLE
Not working with stable Vivaldi version 2.0.1309.42

### ISSUE THREAD

**Issue by NovaViper** [GoogleChromeLabs/picture-in-picture-chrome-extension#3]
I got the recommended flags (#enable-picture-in-picture, #enable-surfaces-for-videos) but it doesn't seem to be working. It does something like this in YouTube: 
![image](https://user-images.githubusercontent.com/7191115/47275747-8c82b180-d577-11e8-99d7-319547d0fdcb.png)

**Comment by beaufortfrancois** [comment]
My best guess is that Vivaldi didn't implement Picture-in-Picture.
@mounirlamouri WDYT?

**Comment by petternilsen** [comment]
It does, but it's only in snapshot versions for the moment.

**Comment by NovaViper** [comment]
@petternilsen Ah that would explain it. I went on the snapshot versions and it's working perfectly! Thanks for the tip!
