### ISSUE TITLE
Add option to disable analytics / tracking

### ISSUE THREAD

**Issue by Electro-Mantis** [GoogleChromeLabs/picture-in-picture-chrome-extension#33]
Just looking at the source and noticed that google analytics data is being from within background.js. There should be a way to opt out of this in the settings in my opinion.

**Comment by beaufortfrancois** [comment]
Thank you @Electro-Mantis!

I've added an option to opt-out of Google Analytics (https://github.com/GoogleChromeLabs/picture-in-picture-chrome-extension/commit/c41fbf4a508d7263f40c5758b4fa7d9bbb1b28f2) and just pushed this to the Webstore. It should be live for everyone in a couple of hours.

![image](https://user-images.githubusercontent.com/634478/61851238-b0807400-aeb6-11e9-8158-6295c407f381.png)


FYI @mounirlamouri

**Comment by felipediogo** [comment]
Shouldn't you close this issue? :D

**Comment by beaufortfrancois** [comment]
Let's close it ;)
