### ISSUE TITLE
Cannot read property 'width' of undefined

### ISSUE THREAD

**Issue by Gotham13121997** [GoogleChromeLabs/picture-in-picture-chrome-extension#36]
The extension fails on the following website https://www.hotstar.com/  with the following error
`VM1604 script.js:22 Uncaught (in promise) TypeError: Cannot read property 'width' of undefined
    at VM1604 script.js:22
    at Array.sort (<anonymous>)
    at VM1604 script.js:19
    at VM1604 script.js:40`

I don't know if it happens with any other website. I am attaching a screenshot as the website may not be available in all countries

![2020-02-01 (1)](https://user-images.githubusercontent.com/26436380/73591616-d0a08800-4516-11ea-884b-f7ff95b39638.png)

Modifying
https://github.com/GoogleChromeLabs/picture-in-picture-chrome-extension/blob/8013674d7b16a068ede318cb95e48fc82ed60d38/src/script.js#L20
https://github.com/GoogleChromeLabs/picture-in-picture-chrome-extension/blob/8013674d7b16a068ede318cb95e48fc82ed60d38/src/script.js#L21

To 
`const v1Rect = v1.getClientRects()[0]||{width:0,height:0};`
`const v2Rect = v2.getClientRects()[0]||{width:0,height:0};`

Fixes the issue

![2020-02-01 (2)](https://user-images.githubusercontent.com/26436380/73591716-1f025680-4518-11ea-9bc3-0b5d9101f188.png)

**Comment by pierophp** [comment]
I'm facing the same problem at https://www.chinesepod.com

**Comment by rohanvakharia** [comment]
@beaufortfrancois Could you please merge #37 pull request?

**Comment by beaufortfrancois** [comment]
Thanks again folks!
