### ISSUE TITLE
the pip sometime shrink by itself in chrome 71.0.3578.98 (Official Build) (64-bit) when watching Twitch

### ISSUE THREAD

**Issue by Syas18** [GoogleChromeLabs/picture-in-picture-chrome-extension#4]

**Comment by beaufortfrancois** [comment]
Thanks @Syas18 for the feedback.
Which platform do you use? Linux, Mac, Windows?
Does "shrink" is the same as "closed"?

**Comment by beaufortfrancois** [comment]
I've fixed PiP window resize algorithm at https://chromiumdash.appspot.com/commit/1874661393200861f053d8af2e861d1866542813. Can you give it a try in Chrome Dev and let me know if that works better for you?

**Comment by Syas18** [comment]
Hi, sorry for late reply. I tried to use  the current pip, and found out that the "shrink" is no longer occur when i set the video quality to auto or change the video quality. I think the problem solve by itself. Maybe the problem is in my pc, not the extension 😅.. So do I still need to do thing you ask me to in your last post(try in chrome dev etc)? sorry for the bad english
