### ISSUE TITLE
Not working on fubo.tv

### ISSUE THREAD

**Issue by aficks** [GoogleChromeLabs/picture-in-picture-chrome-extension#48]
picture-in-picture not working now on fubo.tv please fix it guys thank you

**Comment by polywock** [comment]
Some online TV services like Youtube TV intentionally block Picture-in-Picture functionality for legal reasons.  Fubo.TV might be the same. I made an extension to unblock PiP functionality. Try installing the extension and seeing if it works. Probably not. 

https://chrome.google.com/webstore/detail/djjjomidddlggllpialpgkpnkdaeggfa

**Comment by aficks** [comment]
not working too 😥

**Comment by polywock** [comment]
Have you tried using the new Global Media Controls to enter PiP?

https://techdows.com/2020/02/enable-picture-in-picture-icon-in-global-media-controls-ui-in-chrome.html

**Comment by aficks** [comment]
not working too 😅

**Comment by polywock** [comment]
Try this bookmarklet.  Just create a bookmark and set the URL to the following code.

```
javascript:document.querySelectorAll("video").forEach(v => v.removeAttribute("disablePictureInPicture"));
```

**Comment by aficks** [comment]
whoa man it's working woohoo... thank you so much for helping 🙌🙏🤝 thanks bro!
