### ISSUE TITLE
Block websites from blocking PiP

### ISSUE THREAD

**Issue by Poopooracoocoo** [GoogleChromeLabs/picture-in-picture-chrome-extension#49]
it's annoying and user-hostile.

**Comment by polywock** [comment]
Could you provide some example sites?

**Comment by Poopooracoocoo** [comment]
https://github.com/w3c/picture-in-picture/issues/178
https://w3c.github.io/picture-in-picture/#exit-pip

**Comment by polywock** [comment]
I mean what websites are blocking PiP functionality for you? I wanted to investigate the method they used to block it. There at least two methods. One method used by websites like Youtube TV is through sending a Feature-Policy header. If the website you have a problem with is using the same method. You could try using my extension to unblock it. 

https://github.com/polywock/pipUnblocker

**Comment by Poopooracoocoo** [comment]
Sorry for dodging the question. AnimeLab blocks PiP.

**Comment by polywock** [comment]
I looked into AnimeLab's code. I found two workarounds. The first, use Firefox for AnimeLab. The API they use to block it is not available in Firefox.  The second, use the following bookmark before clicking on the PiP icon. 

```
window.addEventListener("enterpictureinpicture", e => {
    e.stopImmediatePropagation()
}, {capture: true, passive: true})

window.addEventListener("leavepictureinpicture", e => {
    e.stopImmediatePropagation()
}, {capture: true, passive: true})
```

**Comment by Poopooracoocoo** [comment]
Your bookmarklet works! :D

**Comment by beaufortfrancois** [comment]
https://github.com/polywock/pipUnblocker removes `picture-in-picture` feature policy from HTTP headers
All is left is removing the `disablePictureInPicture` HTMLVideoElement attribute.
From there, any website could be forced into Picture-in-Picture mode, even it explicitly told browser it wasn't compatible.

**Comment by polywock** [comment]
@beaufortfrancois, that's technically true, but AnimeLab walls of PiP functionality as a paid feature. To enforce it, they listen to the `enterpictureinpicture` event and forcefully exit using `document.exitPictureInPicture()`. I provided OP with a bookmarklet to block the event propagation. This issue can be closed.

**Comment by Poopooracoocoo** [comment]
@polywock do you think you could merge your bookmarklet and extension and make it automatic? :) sorry if that's not possible or too complicated. I don't really understand how it works. 

i really don't know if websites should really have permission to exit PiP without a user gesture. I can't think of any use cases other than to be user-hostile. it's probably a w3c suggestion or wherever web standards are made though, hence why i made that other issue which got closed. 

i was hoping that Google's PiP extension would add your unblocker. I installed it because I want to make any media go into PiP. If I cared about what websites intended, I wouldn't be using it at all.

**Comment by polywock** [comment]
@Poopooracoocoo, here's an extension version. You'll have to load it yourself. Publishing extensions is a pain. I stopped using a VPN, so I cannot test it on AnimeLab (not available in my country). Let me know if there any issues. 

https://github.com/polywock/pipEventBlocker

**Comment by iamandrewluca** [comment]
Are there any plans to make this extension more intrusive? Like bypass `disablePictureInPicture` and other stuff?

I wrote myself this bookmarklet that also searches for all the videos inside all iframes.

https://gist.github.com/iamandrewluca/71b57cb2d905ab06429c481251db9833
