### ISSUE TITLE
Subtitles will not show up in PIP mode

### ISSUE THREAD

**Issue by gh0sti** [GoogleChromeLabs/picture-in-picture-chrome-extension#6]
sites like Crunchyroll, Netflix, Hulu, ect will not display their subtitles in the PIP screen, anyway to fix this?

**Comment by beaufortfrancois** [comment]
It is a known issue we're aiming to fix eventually. You can star https://crbug.com/854935 to be updated when.

**Comment by Baniita** [comment]
> It is a known issue we're aiming to fix eventually. You can star https://crbug.com/854935 to be updated when.
The link seems broken? Any news?

**Comment by beaufortfrancois** [comment]
Link is not broken for me. No news yet ;(

**Comment by andrizmitnick** [comment]
any news regarding this?

**Comment by cherryleafroad** [comment]
This is a very important feature, I'm missing this too

**Comment by rhonivanpareja** [comment]
> This is a very important feature, I'm missing this too

Agreed, hope that the captions will be implemented soon.

**Comment by Poopooracoocoo** [comment]
Any news?

**Comment by JynZyu** [comment]
Any updates?

**Comment by beaufortfrancois** [comment]
Please star https://crbug.com/854935 to know when it will get implemented.

**Comment by lopugit** [comment]
still not done :'(

**Comment by geodanila** [comment]
Would really love to see this implemented!

**Comment by DFNCTSC** [comment]
This is literally a single setting that needs to be transposed. The fact that it's taken over a year is strange and sad.

**Comment by coffeykevin** [comment]
Maybe just reinstate compact navigation?

**Comment by kyb3r** [comment]
Bruh, this is the only reason why I don't want to use picture in picture. Subtitles don’t work.

**Comment by haleyngonadi** [comment]
Still nothing?

**Comment by petternilsen** [comment]
You can follow https://bugs.chromium.org/p/chromium/issues/detail?id=854935 for when subtitles are implemented in PIP, this is outside the control of this extensions.

**Comment by price1221** [comment]
What

**Comment by alvarovs89** [comment]
waiting for it

**Comment by jpagarcia** [comment]
Waiting for an update.

**Comment by Skrubbe99** [comment]
Same, waiting

**Comment by Poopooracoocoo** [comment]
almost 3 years and zero progress. wow. just wow.

**Comment by petternilsen** [comment]
> almost 3 years and zero progress. wow. just wow.

https://bugs.chromium.org/p/chromium/issues/detail?id=854935 is the issue to comment on, this extension has nothing to do with subtitles and there is nothing it can do to get them.

**Comment by atIOCrON** [comment]
Still waiting...

**Comment by eret9616** [comment]
waiting...

**Comment by rinme** [comment]
waiting.........

**Comment by CJLegacy** [comment]
Waiting...........

**Comment by JGabT** [comment]
waiting.

**Comment by beaufortfrancois** [comment]
See https://github.com/GoogleChromeLabs/picture-in-picture-chrome-extension/issues/6#issuecomment-621707717

**Comment by Poopooracoocoo** [comment]
rest in pepperoni
