### ISSUE TITLE
Keyboard shortcut not working

### ISSUE THREAD

**Issue by rohandhruva** [GoogleChromeLabs/picture-in-picture-chrome-extension#80]
The keyboard shortcut (Option-P) stopped working for me on macOS with Google Chrome Beta and Canary. The only way to trigger PIP is now to press the button in the Chrome toolbar. 

The versions of chrome are: 
* 107.0.5304.18 (Official Build) beta (arm64) 
* 108.0.5338.0 (Official Build) canary (arm64) 

Please let me know what other information will be useful to triage/debug this issue.

**Comment by beaufortfrancois** [comment]
Do you still see the `⌥P` keyboard shortcut  in chrome://extensions/shortcuts?

![image](https://user-images.githubusercontent.com/634478/193760878-46fc4ce5-c6fa-49e6-9e03-8a76b9676368.png)

**Comment by rohandhruva** [comment]
Yes, I confirm that it is still `⌥P` in both the versions of Chrome I shared above.

**Comment by EliaECoyote** [comment]
👋 Had the same issue.
Editing the keyboard shortcut in chrome://extensions/shortcuts and typing `⌥P` again solved it for me.

**Comment by beaufortfrancois** [comment]
Argh. That is sad. I don't know if it's because of the MV3 extension update. I'll ask around.

**Comment by beaufortfrancois** [comment]
FYI I've filed https://bugs.chromium.org/p/chromium/issues/detail?id=1371857 to let the chrome team about this issue

**Comment by luckman212** [comment]
Same issue (macOS + Chrome 106.0.5249.119). Manually editing the keyboard shortcut and re-typing <kbd>⌥P</kbd> "fixed" it for me. Even though prior to doing so, it was already set to that same shortcut.

**Comment by chromer030** [comment]
Same issue , on Linux , ALT + P doesn't work.
Google Chrome 108 
Arch Linux.

**Comment by beaufortfrancois** [comment]
The Chromium team has finally fixed this issue. See https://chromiumdash.appspot.com/commit/a98898b9615f2e454ec02917c720f479f29e673f

It doesn't change anything for this extension as we've upgraded to MV3 already.

**Comment by chromer030** [comment]
@beaufortfrancois , Thanks for the fix , We should wait for version 111 , or it possibly could be backported ?

**Comment by beaufortfrancois** [comment]
I cannot be backported sadly. This extension has been migrated to MV3 already, which means users lost the keyboard shortcut and need to re-add it it again manually in `chrome://extensions/shortcuts`.
