### ISSUE TITLE
PiP window disappears / off-screen after display configuration change

### ISSUE THREAD

**Issue by rohandhruva** [GoogleChromeLabs/picture-in-picture-chrome-extension#89]
I am seeing this issue where the picture in picture window disappears, with no way to "retrieve" it. This happens when I go from multi monitor setup back to laptop display. 

Steps:
- Use laptop connected to a monitor
- Start video playback on display "A"
- Enter PiP mode, to see floating window
- move the PiP floating window to display "B"
- disable PiP mode, video resumes playing on browser window on display "A"
- disconnect the laptop from external monitor
- Resume video playback on the one display now
- Enter PiP mode
- notice that the PiP window is "offscreen", nowhere to be found

Only way to get out of this state is to close that tab and then reopen it. Refreshing the tab does not work. 

This was on macOS 14.5 with Chrome Version 128.0.6541.0 (Official Build) canary (arm64).

**Comment by beaufortfrancois** [comment]
Thanks for reporting this issue @rohandhruva!

Can you open a Chromium bug at https://crbug.com/new and let me know when it's done so that I can ping the Chromium team to fix this issue?

**Comment by beaufortfrancois** [comment]
I've ping the team. Thank you!
